name: deploy release

on:
  workflow_dispatch:
env:
  PROJECT_ID: "eurus-project-dev"
  PROJECT_NUMBER: "103365112501"
permissions:
  contents: 'read'
  id-token: 'write'
jobs:
  deploy-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - id: auth
        name: github-workflow-federation
        uses: google-github-actions/auth@v0.4.3
        with:
          workload_identity_provider: 'projects/${{env.PROJECT_NUMBER}}/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'bucket-create-permission@${{env.PROJECT_ID}}.iam.gserviceaccount.com'
          project_id: ${{ env.PROJECT_ID }}

      - id: get-gke-credentials
        name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v0.4.0
        with:
          cluster_name: cluster-1
          location: us-central1-c
          project_id: ${{ env.PROJECT_ID }}

      - name: kubectl Create Resources
        run: |
          kubectl expose deployment example --port=8765 --target-port=9376 --name=example-service --type=ClusterIP
        #LoadBalancer